# Generated by Django 4.0.3 on 2022-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='white_mode',
            field=models.BooleanField(default=False),
        ),
    ]
