query GetLogbook($user_id: Int!) {
  active_notes(where: {_and: {user_id: {_eq: $user_id}, deleted: {_eq: false}, done: {_eq: true}}}) {
    id
    title
    content
    deadline
    done
    user_id
    project_id
    deleted
    completed_at
  }

  notes_project(where: {_and: {user_id: {_eq: $user_id}, deleted: {_eq: false}, done: {_eq: true}}}) {
    title
    icon
    id
    done
    deleted
    completed_at
  }
}