query GetProjectNotes($project_id: uuid!, $done: Boolean_comparison_exp = {_eq: false}) {
  active_notes(order_by: {position: asc}, where: {_and: {project_id: {_eq: $project_id}, deleted: {_eq: false}, done: $done}}) {
    id
    title
    content
    done
    deadline
    user_id
    project_id
    deleted
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    project{
        title
    }
  }
}