query GetProject($id: bigint!) {
  project: notes_project_by_pk(id: $id) {
    name
    id
    icon
    deleted
    default
    position
    notes {
      id
      position
      title
      deleted
      user_id
      content
      deadline
    }
  }
}