query GetSomedayNotes($user_id: Int!) {
  notes: active_notes(where: {_and: {user_id: {_eq: $user_id}, deadline: {_eq: "1970-01-01"}, deleted: {_eq: false}, done: {_eq: false}}}, order_by: {someday_position: asc}) {
    id
    title
    content
    done
    deadline
    user_id
    project_id
    deleted
    someday_position
  }
}
