query GetTodayNotes($user_id: Int!, $today: date!) {
  active_notes(where: {_and: {user_id: {_eq: $user_id}, deadline: {_lte: $today, _gt: "1970-01-01"}, deleted: {_eq: false}, done: {_eq: false}}}, order_by: {today_position: asc}) {
    id
    title
    content
    done
    deadline
    user_id
    project_id
    deleted
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    project {
      title
    }
  }

  notes_project(where: {_and: {user_id: {_eq: $user_id}, deadline: {_lte: $today, _gt: "1970-01-01"}, deleted: {_eq: false}, done: {_eq: false}}}, order_by: {today_position: asc}) {
    title
    icon
    id
    done
    deleted
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    user_id
  }
}
