query GetTodayNotes($user_id: Int!) {
  notes: notes_note(where: {_and: {user_id: {_eq: $user_id}, deadline: {_eq: Today}, deleted: {_eq: false}, done: {_eq: false}}}) {
    id
    title
    content
    done
    deadline
  }
}
