query GetTrash($user_id: Int!) {
  active_notes(where: {_and: {user_id: {_eq: $user_id}, deleted: {_eq: true}}}) {
    id
    title
    content
    done
    deadline
    user_id
    project_id
    deleted_at
    deleted
  }

  notes_project(where: {_and: {user_id: {_eq: $user_id}, deleted: {_eq: true}, done: {_eq: false}}}) {
    title
    icon
    id
    done
    deleted
    deleted_at
  }
}