query GetUpcomingNotes($user_id: Int!, $today: date!) {
  notes: notes_note(where: {_and: {user_id: {_eq: $user_id}, deadline: {_gt: $today}, deleted: {_eq: false}, done: {_eq: false}}}, order_by: {upcoming_position: asc}) {
    id
    title
    content
    done
    deadline
    user_id
    project_id
    upcoming_position
    deleted
  }
}
