query GetUserData($id: Int!) {
  user: auth_user_by_pk(id: $id){
    id
    username
    admin: is_superuser
    profile{
      id
      avatar
      white_mode
    }
  }
  friends: users_profile_friends(where: {profile: {user_id: {_eq: $id}}}) {
    id
    user {
      id
      username
      profile{
        id
      }
    }
    profile {
      avatar
    }
  }
  projects: notes_project(order_by: {position: asc_nulls_last}, where: {_and: {_or: [{user_id: {_eq: $id}}, {friends: {user_id: {_eq: $id}}}]}, space_id: {_is_null: true}, deleted: {_eq: false}, done: {_eq: false}}) {
    title
    icon
    id
    done
    deleted
    user_id
    completed_at
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    friends {
      user {
        id
        username
        profile {
          avatar
        }
      }
    }
  }
}
