subscription SubscribeSomedayProjects($user_id: Int!) {
  notes_project(where: {_and: {_or: [{user_id: {_eq: $user_id}}, {friends: {user_id: {_eq: $user_id}}}], when: {_eq: "1970-01-01"}, deleted: {_eq: false}, done: {_eq: false}}}, order_by: {someday_position: asc_nulls_last}) {
    title
    icon
    id
    done
    deleted
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    user_id
  }
}
