subscription SubscribeProject($id: uuid!, $done: Boolean_comparison_exp = {_eq: false}) {
  project: notes_project_by_pk(id: $id) {
    title
    id
    icon
    deleted
    position
    done
    notes(order_by: {position: asc}, where: {_and: {deleted: {_eq: false}, done: $done}}) {
      id
      title
      content
      done
      deadline
      user_id
      project_id
      deleted
      anytime_position
      today_position
      someday_position
      anytime_position
      upcoming_position
    }
  }
}