subscription SubscribeProjects($user_id: Int!) {
  projects: notes_project(order_by: {position: asc_nulls_last}, where: {_and: {user_id: {_eq: $user_id}}, space_id: {_is_null: true}, deleted: {_eq: false}, done: {_eq: false}}) {
    title
    icon
    id
    done
    deleted
    user_id
    completed_at
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
  }
}
