subscription SubscribeTrashNotes($user_id: Int!) {
  active_notes: notes_note(where: {_and: {user_id: {_eq: $user_id}, deleted: {_eq: true}}}, order_by: {deleted_at: desc_nulls_last}) {
    id
    title
    content
    done
    when
    user_id
    deleted
    deleted_at
    position
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    project {
      title
      id
    }
  }
}