subscription GetTrashProjects($user_id: Int!) {
  notes_project(where: {_and: {user_id: {_eq: $user_id}, deleted: {_eq: true}}}, order_by: {deleted_at: desc_nulls_last}) {
    title
    icon
    id
    done
    deleted
    deleted_at
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    user_id
  }
}
