subscription SubscribeProjectNotes($project_id: uuid!) {
  notes_note(order_by: {position: asc_nulls_last}, where: {_and: {project_id: {_eq: $project_id}, deleted: {_eq: false}, done: {_eq: false}}}) {
    id
    title
    content
    done
    when
    user_id
    deleted
    repeat
    completed_at
    position
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    project{
        id
        title
    }
  }
}