subscription SubscribeTodayNotes($user_id: Int!, $today: date!) {
  active_notes(where: {_and: {user_id: {_eq: $user_id}, when: {_lte: $today, _gt: "1970-01-01"}, deleted: {_eq: false}, done: {_eq: false}}}, order_by: {today_position: asc_nulls_last}) {
    id
    title
    content
    done
    when
    user_id
    position
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    deleted
    project {
      title
      id
    }
  }
}
