subscription SubscribeUpcomingNotes($user_id: Int!, $today: date!) {
  notes_project(where: {_and: {user_id: {_eq: $user_id}, deadline: {_gt: $today}, deleted: {_eq: false}, done: {_eq: false}}}, order_by: {upcoming_position: asc}) {
    id
    title
    done
    deadline
    user_id
    deleted
    anytime_position
    today_position
    someday_position
    anytime_position
    upcoming_position
    user_id
  }
}