# Generated by Django 4.0.3 on 2022-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_position_space_project_note_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
