# Generated by Django 4.0.3 on 2022-03-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_project_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(default='radio_button_unchecked', max_length=64),
        ),
        migrations.AddField(
            model_name='space',
            name='icon',
            field=models.CharField(default='view_in_ar', max_length=64),
        ),
    ]
