# Generated by Django 4.0.3 on 2022-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_project_icon_space_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
