# Generated by Django 4.0.3 on 2022-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_project_default_alter_project_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(default='radio_button_unchecked', max_length=64),
        ),
        migrations.AlterField(
            model_name='space',
            name='icon',
            field=models.CharField(default='view_in_ar', max_length=64),
        ),
    ]
