# Generated by Django 4.0.3 on 2022-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_note_updated_at_note_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='space',
            name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
