# Generated by Django 4.0.3 on 2022-03-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_remove_note_created_at_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
