# Generated by Django 4.0.3 on 2022-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_note_completed_at_note_done_project_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='done',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='default',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='done',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='space',
            name='deleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='icon',
            field=models.CharField(max_length=64),
        ),
    ]
