# Generated by Django 4.0.3 on 2022-03-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_note_deleted_alter_note_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='default',
        ),
    ]
