# Generated by Django 4.0.3 on 2022-04-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_alter_note_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='today_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='upcoming_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
