# Generated by Django 4.0.3 on 2022-04-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_note_today_position_note_upcoming_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='space',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
