# Generated by Django 4.0.3 on 2022-04-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_note_updated_at_project_updated_at_space_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='name',
            new_name='title',
        ),
    ]
