# Generated by Django 4.0.3 on 2022-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_project_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='today_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='upcoming_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
