# Generated by Django 4.0.3 on 2022-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_remove_note_updated_at_remove_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='anytime_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='someday_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='anytime_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='someday_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
