# Generated by Django 4.0.3 on 2022-04-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_remove_note_id_note_uuiid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='uuiid',
            new_name='id',
        ),
    ]
