# Generated by Django 4.0.3 on 2022-04-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_remove_project_id_remove_space_id_project_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='uuid',
            new_name='id',
        ),
    ]
