# Generated by Django 4.0.3 on 2022-04-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_rename_uuid_project_id_rename_uuid_space_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='space',
        ),
    ]
