# Generated by Django 4.0.3 on 2022-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_note_project_project_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
