# Generated by Django 4.0.3 on 2022-04-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0030_alter_note_completed_at_alter_project_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='deadline',
            new_name='when',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='when',
        ),
    ]
