# Generated by Django 4.0.3 on 2022-05-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0031_rename_deadline_note_when_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='frequency',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
