# Generated by Django 4.0.3 on 2022-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0032_note_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='frequency',
            new_name='repeat',
        ),
    ]
