# Generated by Django 4.0.3 on 2022-05-13 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0033_rename_frequency_note_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
